username ="your username"
password="your password"
host="public host"
port="port"
ad_username="admin name"
ad_password="admin password"
database="db name"

#screen name
object_screen="Select the objects you want to replicate"
destination_page="Select Destination"
destination_db_name="MySQL"
prefix="vinothgopal"
final_screen="every 15 minutes"
db_fetch_query="database query"